print("Hello World")
print("Bye")
print("17*13")
print("Hello python welcome to the world of python")
print("Welcome Priyanshu")
print("Hello")
print("My coding hell")
print("Ahh shit here we go again")
print("Yuddh Karo paarth")
print("Hare Krishna")
print("me and the world")
print(27+12)
